Resources: 
  DDBTable:
    Type: AWS::DynamoDB::Table 
    Properties:
      AttributeDefinitions:

        - AttributeName: ArtistId 
          AttributeType: S 
        
        - AttributeName: Concert 
          AttributeType: S 

      KeySchema:

        - AttributeName: "ArtistId"
          KeyType: "HASH"

        - AttributeName: "Concert"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      TableName: ArtistsTable